inherit_from:
  - enabled.yml
  - disabled.yml
AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
  Exclude:
    - 'vendor/**/*'
  DefaultFormatter: progress
  DisplayCopNames: false
  DisplayStyleGuide: false
  ExtraDetails: false
  StyleGuideCopsOnly: false
  DisabledByDefault: false
  UseCache: true
  MaxFilesInCache: 20000
  CacheRootDirectory: /tmp
  TargetRubyVersion: 2.0
Style/AccessModifierIndentation:
  EnforcedStyle: indent
  SupportedStyles:
    - outdent
    - indent
  IndentationWidth: ~
Style/Alias:
  EnforcedStyle: prefer_alias
  SupportedStyles:
    - prefer_alias
    - prefer_alias_method
Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect
  SupportedLastArgumentHashStyles:
    - always_inspect
    - always_ignore
    - ignore_implicit
    - ignore_explicit
Style/AlignParameters:
  EnforcedStyle: with_first_parameter
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
Style/AndOr:
  EnforcedStyle: always
  SupportedStyles:
    - always
    - conditionals
Style/BarePercentLiterals:
  EnforcedStyle: bare_percent
  SupportedStyles:
    - percent_q
    - bare_percent
Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  SupportedStyles:
    - line_count_based
    - semantic
    - braces_for_chaining
  ProceduralMethods:
    - benchmark
    - bm
    - bmbm
    - create
    - each_with_object
    - measure
    - new
    - realtime
    - tap
    - with_object
  FunctionalMethods:
    - let
    - let!
    - subject
    - watch
  IgnoredMethods:
    - lambda
    - proc
    - it
Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces
  SupportedStyles:
    - braces
    - no_braces
    - context_dependent
Style/CaseIndentation:
  IndentWhenRelativeTo: case
  SupportedStyles:
    - case
    - end
  IndentOneStep: false
  IndentationWidth: ~
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact
Style/ClassCheck:
  EnforcedStyle: is_a?
  SupportedStyles:
    - is_a?
    - kind_of?
Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'
Style/CommandLiteral:
  EnforcedStyle: backticks
  SupportedStyles:
    - backticks
    - percent_x
    - mixed
  AllowInnerBackticks: false
Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW
Style/Copyright:
  Notice: '^Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: ''
Style/DotPosition:
  EnforcedStyle: leading
  SupportedStyles:
    - leading
    - trailing
Style/EmptyElse:
  EnforcedStyle: both
  SupportedStyles:
    - empty
    - nil
    - both
Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: false
Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines
Style/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines
Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines
Style/Encoding:
  EnforcedStyle: always
  SupportedStyles:
    - when_needed
    - always
  AutoCorrectEncodingComment: '# encoding: utf-8'
Style/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: false
Style/FileName:
  Exclude: []
  ExpectMatchingDefinition: false
  Regex: ~
  IgnoreExecutableScripts: true
Style/FirstParameterIndentation:
  EnforcedStyle: special_for_inner_method_call_in_parentheses
  SupportedStyles:
    - consistent
    - special_for_inner_method_call
    - special_for_inner_method_call_in_parentheses
  IndentationWidth: ~
Style/For:
  EnforcedStyle: each
  SupportedStyles:
    - for
    - each
Style/FormatString:
  EnforcedStyle: format
  SupportedStyles:
    - format
    - sprintf
    - percent
Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
  SupportedStyles:
    - when_needed
    - always
Style/GlobalVars:
  AllowedVariables: []
Style/GuardClause:
  MinBodyLength: 1
Style/HashSyntax:
  EnforcedStyle: ruby19
  SupportedStyles:
    - ruby19
    - ruby19_no_mixed_keys
    - hash_rockets
  UseHashRocketsWithSymbolValues: false
Style/IfUnlessModifier:
  MaxLineLength: 80
Style/IndentationConsistency:
  EnforcedStyle: normal
  SupportedStyles:
    - normal
    - rails
Style/IndentationWidth:
  Width: 2
Style/IndentArray:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_brackets
  IndentationWidth: ~
Style/IndentAssignment:
  IndentationWidth: ~
Style/IndentHash:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: ~
Style/LambdaCall:
  EnforcedStyle: call
  SupportedStyles:
    - call
    - braces
Style/Next:
  EnforcedStyle: skip_modifier_ifs
  MinBodyLength: 3
  SupportedStyles:
    - skip_modifier_ifs
    - always
Style/NonNilCheck:
  IncludeSemanticChanges: false
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses
  SupportedStyles:
    - require_parentheses
    - require_no_parentheses
    - require_no_parentheses_except_multiline
Style/MethodName:
  EnforcedStyle: snake_case
  SupportedStyles:
    - snake_case
    - camelCase
Style/MultilineAssignmentLayout:
  SupportedTypes:
    - block
    - case
    - class
    - if
    - kwbegin
    - module
  EnforcedStyle: new_line
  SupportedStyles:
    - same_line
    - new_line
Style/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
  SupportedStyles:
    - aligned
    - indented
  IndentationWidth: ~
Style/MultilineOperationIndentation:
  EnforcedStyle: aligned
  SupportedStyles:
    - aligned
    - indented
  IndentationWidth: ~
Style/NumericLiterals:
  MinDigits: 5
Style/OptionHash:
  SuspiciousParamNames:
    - options
    - opts
    - args
    - params
    - parameters
Style/ParenthesesAroundCondition:
  AllowSafeAssignment: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()
Style/PercentQLiterals:
  EnforcedStyle: lower_case_q
  SupportedStyles:
    - lower_case_q # Use %q when possible, %Q when necessary
    - upper_case_q # Always use %Q
Style/PredicateName:
  NamePrefix:
    - is_
    - has_
    - have_
  NamePrefixBlacklist:
    - is_
    - has_
    - have_
  NameWhitelist:
    - is_a?
Style/RaiseArgs:
  EnforcedStyle: exploded
  SupportedStyles:
    - compact # raise Exception.new(msg)
    - exploded # raise Exception, msg
Style/RedundantReturn:
  AllowMultipleReturnValues: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
  SupportedStyles:
    - slashes
    - percent_r
    - mixed
  AllowInnerSlashes: false
Style/Semicolon:
  AllowAsExpressionSeparator: false
Style/SignalException:
  EnforcedStyle: semantic
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic
Style/SingleLineBlockParams:
  Methods:
    - reduce:
        - a
        - e
    - inject:
        - a
        - e
Style/SingleLineMethods:
  AllowIfMethodIsEmpty: true
Style/SpaceBeforeFirstArg:
  AllowForAlignment: true
Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names
  SupportedStyles:
    - use_perl_names
    - use_english_names
Style/StabbyLambdaParentheses:
  EnforcedStyle: require_parentheses
  SupportedStyles:
    - require_parentheses
    - require_no_parentheses
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: false
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/StringMethods:
  PreferredMethods:
    intern: to_sym
Style/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space
  SupportedStyles:
    - space
    - no_space
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space
Style/SpaceAroundOperators:
  AllowForAlignment: true
Style/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space
Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SupportedStyles:
    - space
    - no_space
Style/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space
  SupportedStyles:
    - space
    - no_space
Style/SymbolArray:
  EnforcedStyle: percent
  SupportedStyles:
    - percent
    - brackets
Style/SymbolProc:
  IgnoredMethods:
    - respond_to
Style/TrailingBlankLines:
  EnforcedStyle: final_newline
  SupportedStyles:
    - final_newline
    - final_blank_line
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
  SupportedStyles:
    - comma
    - consistent_comma
    - no_comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma
  SupportedStyles:
    - comma
    - consistent_comma
    - no_comma
Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: false
  AllowDSLWriters: false
  IgnoreClassMethods: false
  Whitelist:
    - to_ary
    - to_a
    - to_c
    - to_enum
    - to_h
    - to_hash
    - to_i
    - to_int
    - to_io
    - to_open
    - to_path
    - to_proc
    - to_r
    - to_regexp
    - to_str
    - to_s
    - to_sym
Style/VariableName:
  EnforcedStyle: snake_case
  SupportedStyles:
    - snake_case
    - camelCase
Style/WhileUntilModifier:
  MaxLineLength: 80
Style/WordArray:
  EnforcedStyle: percent
  SupportedStyles:
    - percent
    - brackets
  MinSize: 0
  WordRegex: !ruby/regexp '/\A[\p{Word}\n\t]+\z/'
Metrics/AbcSize:
  Max: 15
Metrics/BlockNesting:
  Max: 3
Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 100
Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 6
Metrics/LineLength:
  Max: 80
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 10
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true
Metrics/PerceivedComplexity:
  Max: 7
Lint/AssignmentInCondition:
  AllowSafeAssignment: true
Lint/EndAlignment:
  AlignWith: keyword
  SupportedStyles:
    - keyword
    - variable
    - start_of_line
  AutoCorrect: false
Lint/DefEndAlignment:
  AlignWith: start_of_line
  SupportedStyles:
    - start_of_line
    - def
  AutoCorrect: false
Lint/UnusedBlockArgument:
  IgnoreEmptyBlocks: true
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: false
  IgnoreEmptyMethods: true
Rails/ActionFilter:
  EnforcedStyle: action
  SupportedStyles:
    - action
    - filter
  Include:
    - app/controllers/**/*.rb
Rails/Date:
  EnforcedStyle: flexible
  SupportedStyles:
    - strict
    - flexible
Rails/FindBy:
  Include:
    - app/models/**/*.rb
Rails/FindEach:
  Include:
    - app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Include:
    - app/models/**/*.rb
Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb
Rails/ReadWriteAttribute:
  Include:
    - app/models/**/*.rb
Rails/ScopeArgs:
  Include:
    - app/models/**/*.rb
Rails/TimeZone:
  EnforcedStyle: flexible
  SupportedStyles:
    - strict
    - flexible
Rails/Validation:
  Include:
    - app/models/**/*.rb
